import streamlit as st
from datetime import datetime
import json
from video_prompt_generator import VideoPromptGenerator, VideoScenePrompts

st.set_page_config(
    page_title="AI Video Prompt Refiner",
    page_icon="🎬",
    layout="wide",
    initial_sidebar_state="expanded"
)

st.markdown("""
<style>
    .main-header {
        background: linear-gradient(90deg, #667eea 0%, #764ba2 100%);
        padding: 2rem;
        border-radius: 10px;
        color: white;
        text-align: center;
        margin-bottom: 2rem;
    }
    .prompt-card {
        background: linear-gradient(135deg, #f5f7fa 0%, #c3cfe2 100%);
        padding: 1.5rem;
        border-radius: 10px;
        margin: 1rem 0;
        border-left: 5px solid #667eea;
        box-shadow: 0 4px 6px rgba(0, 0, 0, 0.1);
    }
    .scene-title {
        color: #667eea;
        font-weight: bold;
        font-size: 1.2em;
        margin-bottom: 0.5rem;
    }
    .success-message {
        background-color: #d4edda;
        border: 1px solid #c3e6cb;
        color: #155724;
        padding: 1rem;
        border-radius: 5px;
        margin: 1rem 0;
    }
</style>
""", unsafe_allow_html=True)

st.markdown("""
<div class="main-header">
    <h1>🎬 AI Video Prompt Refiner</h1>
    <p>Enter your business/script and instantly see refined, professional video prompts generated by AI</p>
    <small>💡 Powered by Gemini API</small>
</div>
""", unsafe_allow_html=True)

with st.expander("💡 See Example Inputs", expanded=False):
    st.markdown("""
    **Restaurant Example:**
    ```
    I run Green Garden Cafe, a sustainable farm-to-table restaurant in downtown. 
    We source ingredients locally, offer organic dishes, and create a cozy atmosphere 
    for families and professionals. I want videos showcasing our fresh ingredient 
    preparation, happy customers, cozy atmosphere, and sustainability commitment.
    ```
    **Tech Company Example:**
    ```
    I run TechFlow Solutions, a software development company specializing in AI automation. 
    We help businesses streamline operations through intelligent automation and cloud solutions. 
    I want professional videos showing our modern office, team collaboration, AI solutions 
    in action, and client testimonials that convey innovation and expertise.
    ```
    **Real Estate Example:**
    ```
    I run iCONNCT, a real estate technology platform that works like Uber for real estate. 
    We offer instant agent connections, video calls, and seamless property tours. 
    I want videos demonstrating our technology, showing agents helping clients, 
    property showcases, and satisfied customers.
    ```
    """)

st.subheader("📝 Enter Your Script/Business Description")
user_input = st.text_area(
    "Describe your business and video goals:",
    placeholder="Enter your company description, script, and any requirements...",
    height=200
)

if st.button("🚀 Generate & Refine Prompts", type="primary", use_container_width=True, disabled=not user_input or len(user_input.split()) < 15):
    with st.spinner("Generating refined video prompts..."):
        try:
            generator = VideoPromptGenerator()
            prompts = generator.generate_video_prompts(user_input)
            st.session_state['last_prompts'] = prompts
            st.session_state['last_input'] = user_input
            st.session_state['last_time'] = datetime.now().strftime('%Y-%m-%d %H:%M:%S')
        except Exception as e:
            st.error(f"❌ Error: {e}")

if 'last_prompts' in st.session_state:
    prompts = st.session_state['last_prompts']
    st.markdown("""
    <div class="success-message">
        <h3>🎉 Refined Video Prompts Generated!</h3>
        <p>Review the AI-generated scene prompts below. Each is tailored to your input.</p>
    </div>
    """, unsafe_allow_html=True)
    scenes = [
        ("Scene 1", prompts.prompt_1, "🌟"),
        ("Scene 2", prompts.prompt_2, "🎯"),
        ("Scene 3", prompts.prompt_3, "✅"),
        ("Scene 4", prompts.prompt_4, "🚀")
    ]
    cols = st.columns(2)
    for i, (title, prompt, emoji) in enumerate(scenes):
        with cols[i % 2]:
            st.markdown(f"""
            <div class="prompt-card">
                <div class="scene-title">{emoji} {title}</div>
                <div style='color: #666; line-height: 1.6;'>
                    {prompt[:200]}{'...' if len(prompt) > 200 else ''}
                </div>
                <div style='margin-top: 1rem; font-size: 0.9em; color: #888;'>
                    Length: {len(prompt)} characters
                </div>
            </div>
            """, unsafe_allow_html=True)
    st.markdown("---")
    # Dropdown for full scene selection
    scene_options = [f"{emoji} {title}" for title, _, emoji in scenes]
    selected_scene = st.selectbox(
        "🔽 Select a scene to view full prompt:",
        options=scene_options,
        index=0
    )
    # Show full prompt for selected scene
    selected_idx = scene_options.index(selected_scene)
    full_title, full_prompt, full_emoji = scenes[selected_idx]
    st.markdown(f"### {full_emoji} {full_title} - Full Prompt")
    st.text_area(
        label=f"Full prompt for {full_title}",
        value=full_prompt,
        height=250,
        disabled=True
    )
    st.markdown("---")
    st.markdown(f"**Input Provided:**\n\n> {st.session_state['last_input']}")
    st.markdown(f"**Generated At:** {st.session_state['last_time']}")
    # Download as JSON
    prompts_dict = {
        "input": st.session_state['last_input'],
        "generated_at": st.session_state['last_time'],
        "prompts": {
            "scene_1": prompts.prompt_1,
            "scene_2": prompts.prompt_2,
            "scene_3": prompts.prompt_3,
            "scene_4": prompts.prompt_4
        }
    }
    json_data = json.dumps(prompts_dict, indent=2)
    st.download_button(
        label="📥 Download Prompts as JSON",
        data=json_data,
        file_name=f"refined_video_prompts_{datetime.now().strftime('%Y%m%d_%H%M%S')}.json",
        mime="application/json"
    )
